# Generated by Django 6.1 on 2026-09-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_package_payment_type_package_recipient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_type',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(default='UNKNOWN', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.employee')),
                ('packages', models.ManyToManyField(to='shipments.package')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.vehicle')),
            ],
        ),
    ]
