# Generated by Django 6.1 on 2026-09-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_vehicle_alter_package_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_packages', to='shipments.branch'),
        ),
    ]
