# Generated by Django 6.1 on 2026-09-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_sefer_delete_vehicleloading'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_branches', to='shipments.branch')),
            ],
        ),
    ]
