# Generated by Django 6.1 on 2026-09-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_remove_sefer_packages_package_sefer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefer',
            name='previous_sefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_seferler', to='shipments.sefer'),
        ),
    ]
