# Generated by Django 6.1 on 2026-09-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_sefer_previous_sefer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('LOADING', 'Yükleniyor'), ('IN_TRANSIT', 'Yolda'), ('ARRIVED', 'Vardı'), ('COMPLETED', 'Tamamlandı')], max_length=20)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_destinations', to='shipments.branch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_origins', to='shipments.branch')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='shipments.package')),
                ('sefer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_histories', to='shipments.sefer')),
            ],
        ),
    ]
