# Generated by Django 6.1 on 2026-09-10 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_packagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehistory',
            name='sequence_no',
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Kargoya Verildi'), ('IN_TRANSIT', 'Yola Çıktı'), ('AT_BRANCH', 'Şubeye Ulaştı'), ('OUT_FOR_DELIVERY', 'Dağıtıma Çıktı'), ('DELIVERED', 'Teslim Edildi')], max_length=20),
        ),
    ]
