# Generated by Django 6.1 on 2026-09-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_remove_packagehistory_sequence_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehistory',
            name='sefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_histories', to='shipments.sefer'),
        ),
    ]
