# Generated by Django 6.1 on 2026-09-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_alter_packagehistory_sefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehistory',
            name='destination_branch',
        ),
        migrations.RemoveField(
            model_name='packagehistory',
            name='origin_branch',
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dfsifdskfdsğ', to='shipments.branch'),
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.employee'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('AT_BRANCH', 'Şubeye Ulaştı'), ('LEAVE_BRANCH', 'Şubeden Ayrıldı.'), ('IN_TRANSIT', 'Yolda'), ('LEFT_TRANSIT', 'Sefer bitti'), ('OUT_FOR_DELIVERY', 'Dağıtıma Çıktı'), ('DELIVERED', 'Teslim Edildi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planlandı'), ('IN_TRANSIT', 'Yolda'), ('COMPLETED', 'Tamamlandı')], default='PLANNED', max_length=20),
        ),
    ]
