# Generated by Django 6.1 on 2026-08-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_packages', to='shipments.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.employee')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_packages', to='shipments.branch')),
            ],
        ),
    ]
