# Generated by Django 6.1 on 2026-09-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
