# Generated by Django 6.1 on 2026-09-07 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_package_current_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('LOADING', 'Yükleniyor'), ('IN_TRANSIT', 'Yolda'), ('ARRIVED', 'Vardı'), ('COMPLETED', 'Tamamlandı')], default='PLANNED', max_length=20)),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_destinations', to='shipments.branch')),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.employee')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_origins', to='shipments.branch')),
                ('packages', models.ManyToManyField(to='shipments.package')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleLoading',
        ),
    ]
