# Generated by Django 6.1 on 2026-09-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_localbranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sefer',
            name='packages',
        ),
        migrations.AddField(
            model_name='package',
            name='sefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='shipments.sefer'),
        ),
        migrations.DeleteModel(
            name='LocalBranch',
        ),
    ]
