# Generated by Django 6.1 on 2026-09-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_remove_packagehistory_destination_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sefer',
            name='previous_sefer',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('AT_BRANCH', 'Şubede'), ('IN_TRANSIT', 'Yolda'), ('OUT_FOR_DELIVERY', 'Dağıtımda'), ('DELIVERED', 'Teslim Edildi'), ('DELIVERY_FAILED', 'Teslim Edilemedi')], db_index=True, default='AT_BRANCH', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_histories', to='shipments.branch'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('AT_BRANCH', 'Şubeye Ulaştı'), ('LEAVE_BRANCH', 'Şubeden Ayrıldı.'), ('IN_TRANSIT', 'Yolda'), ('LEFT_TRANSIT', 'Sefer bitti'), ('OUT_FOR_DELIVERY', 'Dağıtıma Çıktı'), ('DELIVERED', 'Teslim Edildi'), ('DELIVERY_FAILED', 'Teslim Edilemedi')], max_length=20),
        ),
    ]
