# Generated by Django 6.1 on 2026-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehistory',
            name='status',
            field=models.CharField(choices=[('AT_BRANCH', 'Şubeye Ulaştı'), ('LEAVE_BRANCH', 'Şubeden Ayrıldı.'), ('IN_TRANSIT', 'Yolda'), ('LEFT_TRANSIT', 'Sefer bitti'), ('OUT_FOR_DELIVERY', 'Dağıtıma Çıktı'), ('DELIVERED', 'Teslim Edildi')], max_length=20),
        ),
    ]
