# Generated by Django 6.1 on 2026-09-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_rename_sefer_trip_employee_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY_TO_GO', 'Dağıtıma Hazır'), ('OUT_FOR_DELIVERY', 'Dağıtımda'), ('COMPLETED', 'Tamamlandı')], default='READY_TO_GO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='shipments.branch')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='shipments.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='shipments.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_histories', to='shipments.distribution'),
        ),
        migrations.CreateModel(
            name='DistributionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PENDING', 'Bekliyor'), ('DELIVERED', 'Teslim Edildi'), ('FAILED', 'Teslim Edilemedi')], default='PENDING', max_length=20)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shipments.distribution')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='shipments.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('distribution', 'package'), name='unique_distribution_package')],
            },
        ),
    ]
